openapi: 3.0.0
info:
  title: LifePlanner Service - OpenAPI 1.0
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/notepad
tags:
  - name: Folder
    description: Folder API
  - name: Notebook
    description: Notebook API
  - name: Note
    description: Note API
paths:
  /v1/folder:
    post:
      operationId: createFolder
      summary: Create new folder
      tags:
        - Folder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FolderDto'
        required: true
      responses:
        '201':
          description: Folder is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FolderDto'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

    get:
      operationId: getAllFolders
      summary: Get all folders
      tags:
        - Folder
      responses:
        '200':
          description: Folders are gotten
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFolderDto'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


  /v1/folder/{id}:
    put:
      operationId: updateFolder
      summary: Update folder
      tags:
        - Folder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: String
            format: uuid
        - in: query
          name: name
          required: false
          schema:
            type: String
      responses:
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

    delete:
      operationId: deleteFolder
      summary: Delete folder
      tags:
        - Folder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: String
            format: uuid
      responses:
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


  /v1/notebook:
    post:
      operationId: createNotebook
      summary: Create new notebook
      tags:
        - Notebook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotebookDto'
        required: true
      responses:
        '201':
          description: Notebook is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotebookDto'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


  /v1/notebook/{id}:
    put:
      operationId: updateNotebook
      summary: Update notebook
      tags:
        - Notebook
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: String
            format: uuid
        - in: query
          name: name
          required: false
          schema:
            type: String
      responses:
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
    delete:
      operationId: deleteNotebook
      summary: Delete notebook
      tags:
        - Notebook
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: String
            format: uuid
      responses:
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


  /v1/note:
    post:
      operationId: createNote
      summary: Create new note
      tags:
        - Note
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteDto'
        required: true
      responses:
        '201':
          description: Note is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteDto'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /v1/note/{id}:
    put:
      operationId: updateNote
      summary: Update note
      tags:
        - Note
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: String
            format: uuid
        - in: query
          name: name
          required: false
          schema:
            type: String
      responses:
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '401':
          description: Not authorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '405':
          description: Method is not available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

components:
  schemas:
    ErrorResponseDto:
      type: object
      properties:
        message:
          type: string
          description: Error message
        code:
          type: integer
          description: Error status code
        traceId:
          type: string
          description: Trace Id

    ListFolderDto:
      type: object
      properties:
        folders:
          type: array
          items:
            $ref: '#/components/schemas/FolderDto'

    FolderDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: false
          description: Name of folder
        notebooks:
          type: array
          items:
            $ref: '#/components/schemas/NotebookDto'

    NotebookDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        folderId:
          type: string
          format: uuid
        name:
          type: string
          nullable: false
          description: Name of folder
        notes:
          type: array
          items:
            $ref: '#/components/schemas/NoteDto'

    NoteDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        notebookId:
          type: string
          format: uuid
        name:
          type: string
          nullable: false
        text:
          type: string