server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true

  liquibase:
    change-log: classpath:changelog/db.changelog-master.yaml
    default-schema: notepad
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/fixchaos?currentSchema=notepad}
    username: ${DB_USER:postgres_user}
    password: ${DB_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver