server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:changelog/db.changelog-master.yaml
    default-schema: planning

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/fixchaos?currentSchema=planning}
    username: ${DB_USER:postgres_user}
    password: ${DB_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver