#У тестов, реализованных как через in memory db, так и через тест контейнеры суть одна.
#Создается сущность (in memory db или контейнер), дальше объявляется data source с параметрами
#подключения, подходящими к этим сущностям, далее происходит применение миграций и работа с этими сущностями
#в рамках обычных запросов, происходящих в тестируемых методах
spring:
  liquibase:
    change-log: classpath:integrationTestdb/changelog/db.changelog-master.yaml
  datasource:
    url: ${CONTAINER.URL}
    username: ${CONTAINER.USERNAME}
    password: ${CONTAINER.PASSWORD}
  security:
    user:
      password: password